# examples:
#   periodic_cleanup:
#     class: CleanSoftDeletedRecordsJob
#     queue: background
#     args: [ 1000, { batch_size: 500 } ]
#     schedule: every hour
#   periodic_cleanup_with_command:
#     command: "SoftDeletedRecord.due.delete_all"
#     priority: 2
#     schedule: at 5am every day

production:
  clear_solid_queue_finished_jobs:
    command: "SolidQueue::Job.clear_finished_in_batches(sleep_between_batches: 0.3)"
    schedule: every hour at minute 12
  teamtailor_sync:
    command: "TeamtailorSyncJob.perform_later"
    schedule: every 30 seconds
  teamtailor_backfill:
    command: "TeamtailorBackfillJob.perform_later"
    schedule: at 3am every day
  teamtailor_backfill_answers:
    command: "TeamtailorBackfillAnswersJob.perform_later"
    schedule: every 5 minutes
  teamtailor_desync_check:
    command: "TeamtailorDesyncCheckJob.perform_later"
    schedule: every 5 minutes
  education_extraction:
    command: "EducationExtractionJob.perform_later"
    schedule: every 1 minute
  cv_backfill:
    command: "CvBackfillJob.perform_later"
    schedule: every 1 minute
